env:
  global:
    - PACKAGE="Assembly-6809"
    - SUBLIME_TEXT_VERSION="3"

os:
  - linux

language: python

services:
  - xvfb

before_install:
  - curl -OL https://raw.githubusercontent.com/SublimeText/UnitTesting/master/sbin/travis.sh

install:
  - sh travis.sh bootstrap

script:
  - sh travis.sh run_syntax_tests
  - sh travis.sh run_syntax_compatibility

notifications:
  email:
    on_success: change
    on_failure: always
