env:
  global:
    - PACKAGE="Assembly-6809"
    - SUBLIME_TEXT_VERSION="3"

os:
  - linux

language: python

before_install:
  - curl -OL https://raw.githubusercontent.com/SublimeText/UnitTesting/master/sbin/travis.sh
  - if [ "$TRAVIS_OS_NAME" == "linux"  ]; then
          export DISPLAY=:99.0;
          sh -e /etc/init.d/xvfb start;
    fi

install:
  - sh travis.sh bootstrap

script:
  - sh travis.sh run_syntax_tests
  - sh travis.sh run_syntax_compatibility

notifications:
  email:
    on_success: change
    on_failure: always
